apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: transacanalyzer-serving-template
  annotations:
    scenarios.ai.sap.com/description: "Serving template for transacanalyzer"
    scenarios.ai.sap.com/name: "transacanalyzer"
    executables.ai.sap.com/description: "Serving executable for transacanalyzer"
    executables.ai.sap.com/name: "transacanalyzer-executable"
  labels:
    scenarios.ai.sap.com/id: "transacanalyzer"
    executables.ai.sap.com/id: "transacanalyzer-executable"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters: []
    artifacts: []
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: '{"autoscaling.knative.dev/metric": "concurrency", "autoscaling.knative.dev/target": "1"}'
      labels: '{"ai.sap.com/resourcePlan": "starter"}'
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 2
        containers:
          - name: transaction-analyzer
            image: docker.io/jerushan/transaction-analyzer-rnd:latest
            ports:
              - containerPort: 8080
            env:
              - name: MODEL
                value: "production"
            resources:
              limits:
                cpu: "1"
                memory: "2Gi"
              requests:
                cpu: "0.5"
                memory: "1Gi"
